### ISSUE TITLE
mail content is not readable at all. 

### ISSUE THREAD

**Issue by kotran88** [Enough-Software/enough_mail_app#84]
I just run sample app 
but when I see each mail's detail , 
it cause only loading bar on content-arts

saying
```

 [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Unknown feature REQUESTED_WITH_HEADER_CONTROL, null, java.lang.RuntimeException: Unknown feature REQUESTED_WITH_HEADER_CONTROL
E/flutter ( 3555):      at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:574)
E/flutter ( 3555):      at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:543)
E/flutter ( 3555):      at androidx.webkit.WebViewFeature.isFeatureSupported(WebViewFeature.java:567)
E/flutter ( 3555):      at com.pichillilorenzo.flutter_inappwebview.webview.in_app_webview.InAppWebView.prepare(InAppWebView.java:436)
E/flutter ( 3555):      at com.pichillilorenzo.flutter_inappwebview.webview.in_app_webview.FlutterWebView.<init>(FlutterWebView.java:84)
E/flutter ( 3555):      at com.pichillilorenzo.flutter_inappwebview.FlutterWebViewFactory.create(FlutterWebViewFactory.java:44)
E/flutter ( 3555):      at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:503)
E/flutter ( 3555):      at io.flutter.plugin.platform.PlatformViewsController$1.createForPlatformViewLayer(PlatformViewsController.java:163)
E/flutter ( 3555):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:105)
E/flutter ( 3555):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
E/flutter ( 3555):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/flutter ( 3555):      at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter ( 3555):      at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter ( 3555):      at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 3555):      at android.os.Handler.handleCallback(Handler.java:942)
E/flutter ( 3555):      at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 3555):      at android.os.Looper.loopOnce(Looper.java:226)
E/flutter ( 3555):      at android.os.Looper.loop(Looper.java:313)
E/flutter ( 3555):      at android.app.ActivityThread.main(ActivityThread.java:8757)
E/flutter ( 3555):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 3555):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/flutter ( 3555):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
E/flutter ( 3555): )
E/flutter ( 3555): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter ( 3555): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
E/flutter ( 3555): <asynchronous suspension>
E/flutter ( 3555): #2      ExpensiveAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1081:5)
E/flutter ( 3555): <asynchronous suspension>
E/flutter ( 3555): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:801:5)
E/flutter ( 3555): <asynchronous suspension>
E/flutter ( 3555): 
```

**Comment by hashirawan01** [comment]
hey @kotran88 can you just tell me how can you run this application on your local machine when im tryig to run it gives me tis error Target file "lib\main.dart" not found.
can you please help
